version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: quiz_builder_db
    environment:
      POSTGRES_DB: quiz_builder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz_builder_network

  app:
    build: .
    container_name: quiz_builder_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=quiz_builder
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=7d
      - PORT=3000
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - postgres
    networks:
      - quiz_builder_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:

networks:
  quiz_builder_network:
    driver: bridge 