services:
  mysql:
    image: mysql:8.4
    container_name: quizzes_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: quizzes
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge